"""empty message

Revision ID: a0ae7d22cdfc
Revises: c3b70f1a1786
Create Date: 2022-10-17 15:49:13.369744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ae7d22cdfc'
down_revision = 'c3b70f1a1786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'description',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
    # ### end Alembic commands ###
