"""empty message

Revision ID: c3b70f1a1786
Revises: 2db9c079d67b
Create Date: 2022-09-12 11:56:07.881622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b70f1a1786'
down_revision = '2db9c079d67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('context', sa.String(length=200), nullable=True))
    op.drop_column('review', 'review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('review', 'context')
    # ### end Alembic commands ###
